# Generated by Django 3.2.18 on 2023-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover_images/default.jpg', null=True, upload_to='cover_images'),
        ),
    ]
