# Generated by Django 4.1.7 on 2023-03-24 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_card_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_userprofile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_amount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
