# Generated by Django 4.1.7 on 2023-03-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_card_balance'),
        ('users', '0005_coinamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coinamount',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coinamount',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='coins.coin'),
        ),
    ]
