# Generated by Django 4.1.7 on 2023-03-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.FloatField(default=15000),
        ),
    ]
